# Generated by Django 6.0.4 on 2026-04-15 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_time", models.DateTimeField()),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                ("capacity", models.IntegerField(default=10)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("image", models.URLField(blank=True, default="", max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technology", "Technology"),
                            ("business", "Business"),
                            ("design", "Design"),
                            ("marketing", "Marketing"),
                            ("health", "Health & Wellness"),
                            ("education", "Education"),
                            ("finance", "Finance"),
                            ("arts", "Arts & Culture"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "sessions", "ordering": ["-date_time"],},
        ),
    ]
